// Re-exports of generated OpenAPI schema types (see
// src/api/generated/schema.ts, regenerated by `make generate-api-types`
// from the backend's pydantic models) -- kept as this file's own named
// exports so every existing import site (`from "../types/auth"`) needs no
// changes. Backend schema names differ from these two; alias explicitly.
// Do not hand-edit these shapes; edit the backend model and regenerate
// instead.
import type { components } from "../api/generated/schema";

export type ApiTokenMeta = components["schemas"]["ApiTokenMeta"];
export type CreateApiTokenResult = components["schemas"]["CreateApiTokenResponse"];
export type AccountSummary = components["schemas"]["AccountSummary"];
export type CreateInviteResult = components["schemas"]["CreateInviteResponse"];
export type LoginResponse = components["schemas"]["LoginResponse"];
