// Re-exports of generated OpenAPI schema types (see
// src/api/generated/schema.ts, regenerated by `make generate-api-types`
// from the backend's pydantic models) -- kept as this file's own named
// exports so every existing import site (`from "../types/note"`) needs no
// changes. Do not hand-edit these shapes; edit the backend model and
// regenerate instead.
import type { components } from "../api/generated/schema";

export type NoteMeta = components["schemas"]["NoteMeta"];
export type Note = components["schemas"]["Note"];
export type GraphNode = components["schemas"]["GraphNode"];
export type GraphEdge = components["schemas"]["GraphEdge"];
export type GraphResponse = components["schemas"]["GraphResponse"];
export type AttachmentUploadResult = components["schemas"]["AttachmentUploadResponse"];
